Quickstart documentation
neo-one-suite/neo-one pull request #2338
Opened 2021-02-23 00:20 UTC by ndhuutai

### Requirements

Quickstart documentation.

### Description of the Change

Added a new Quickstart page.

### Test Plan

N/A

### Alternate Designs

N/A

### Benefits

The new Quickstart page will give new developers better overview of the development and deploy flow with Neo-One.

### Possible Drawbacks

N/A

### Applicable Issues

N/A

2021-02-23 21:22 UTC, spencercorwin requested changes

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +6. Save the private key shown on screen locally and secure it.
Save your private key somewhere secure.

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +7. Click continue to view your wallet.
Click `Continue` to view your wallet.

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +8. (Optional) Generate a PDF by clicking on “Print paper wallet”
"...a PDF of your wallet..."

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +8. (Optional) Generate a PDF by clicking on “Print paper wallet”
Surround "Print paper wallet" in backticks like you do everywhere else: `"Print paper wallet"`.

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +9. (Optional) Scroll down to `“Details”` when viewing your wallet to access the options of the previous steps (such as to view your private key or download keystore file).
"...or download a keystore file..."

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +Create a `migration.ts` (`migration.js` if using JS) under `neo-one` folder.
"Create a `migration.ts` (`migration.js` if using JS) at the path specified in your NEO•ONE configuration file".

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +VSCode might display single child folders in "compact form" and prevent you from creating a new file under neo-one. Disable "compact folder" in "settings" if needed.
Change "VSCode" to "Visual Studio Code" to be as clear as possible.

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +- Test coins only show on TestNet. Use https://testnet.neotracker.io to explore transactions and use the wallet on TestNet.
"You should then be able to see the assets in your wallet at https://testnet.neotracker.io"

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +yarn neo-one deploy --network [network-name]
"yarn neo-one deploy --network <network>"

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +Where `network` is one of the keys provided by your configuration (`.neo-one.config.ts`) under `networks` property. By default yarn neo-one deploy will use the test key.
"... under the `networks` property."

"By default `neo-one deploy` will use the `test` key."

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +## Explore with Neo Tracker
"...with NEO Tracker"

NEO Tracker, our web app, is capitalized

2021-02-23 21:22 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +If you deployed in TestNet, you can check out https://testnet.neotracker.io/. Otherwise, use https://neotracker.io.
"If your deployment was successful you should be able to find your contract at https://testnet.neotracker.io/browse/contract/1"

2021-02-25 00:44 UTC, ndhuutai commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +- If you want to learn with a real-world example, check out our [Course](/course) which you can follow and see how things are tested. Also keep [Docs](/docs/hello-world) page handy for reference.
Changed. Thanks!

2021-02-25 00:45 UTC, ndhuutai commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +1. Install [Node](https://nodejs.org) >= 10.16.0 (Latest version recommended)
Modified. Thx.

2021-02-25 00:46 UTC, ndhuutai commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +The command above generates a sample `HelloWorld.ts` smart contract, a sample test for the contract `HelloWorld.test.ts`, a config file `.neo-one.config.ts`, and `neo-one` folder with important modul
Modified. Thx.

2021-02-25 19:07 UTC, spencercorwin commented on packages/neo-one-website/docs/0-installation/0-quick-start.md
> +yarn neo-one deploy --network [network-name]
Whoops. My comment supposed to say `yarn neo-one deploy --network <network>`

2021-02-25 20:34 UTC, closed without merging