fix: pino prettyPrint
neo-one-suite/neo-one pull request #2345
Opened 2021-03-04 22:59 UTC by ndhuutai

### Description of the Change

Modified loggers.ts to set prettyPrint to true for cli "service". Before the change, prettyPrint was not set to true (despite being called in init.ts in neo-one-cli) because init.ts was executed after loggers.ts (which creates different loggers for different environments.) 
Before:
![Screen Shot 2021-03-04 at 12 26 25 PM](https://user-images.githubusercontent.com/30916803/110040317-749acb00-7cf7-11eb-90a1-fdd613f24037.png)
After:
![Screen Shot 2021-03-04 at 2 42 10 PM](https://user-images.githubusercontent.com/30916803/110040525-d0655400-7cf7-11eb-81c0-002584c33896.png)

### Test Plan

1. Create symlinks for @neo-one/cli and @neo-one/smart-contract-typescript-plugin packages with 'yarn link'
2. Create and init a neo-one project. 
3. Apply the links to the above packages.
4. Intentionally add erroneous code.
5. Run yarn neo-one build.

For more details on symlinking check out [yarn docs on link](https://classic.yarnpkg.com/en/docs/cli/link/)

### Alternate Designs

N/A

### Benefits

Outputs better error message.

### Possible Drawbacks

N/A

### Applicable Issues

#2069

2021-03-08 19:04 UTC, spencercorwin requested changes
I'm not sure what happened with `neo-one-cli/bin/neo-one.js` but it shouldn't be empty

2021-03-08 19:04 UTC, spencercorwin commented on packages/neo-one-smart-contract-compiler/src/api.ts
> +  throwOnDiagnosticErrorOrWarning(result.diagnostics, ignoreWarnings, 'Error while compiling contract(s)');
Let's put the contract name here to make it a little cleaner. So it's `'Error while compiling contract ${contractName}'`

And change `_contractName` to `contractName`

2021-03-08 19:04 UTC, spencercorwin commented on packages/neo-one-smart-contract-compiler/src/utils/throwOnDiagnosticErrorOrWarning.ts
> +  message: string = 'There was an error',
Can we just make this an empty string? That seems cleaner

2021-03-10 19:46 UTC, ndhuutai reviewed
neo-one.js was untouched. The file still exists.

2021-03-10 21:51 UTC, spencercorwin approved these changes

2021-03-10 21:52 UTC, merged